import Head from "next/head";

import NewsTicker from "@/components/NewsTicker";

import { useState, useRef, useEffect } from "react";
import { useRouter } from "next/router";
import FooterSection from "./FooterSection";
import Navbar from "./HeaderSection";
import { CartProvider } from "../add-to-cart/components/CartContext";
import CartSlider from "../add-to-cart/components/CartSlider";
import { Toaster } from "react-hot-toast";

export default function Layout({ children }) {
  const [servicesOpen, setServicesOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const servicesRef = useRef(null);
  const mobileMenuRef = useRef(null);
  const router = useRouter();

  useEffect(() => {
    function handleClickOutside(event) {
      if (servicesRef.current && !servicesRef.current.contains(event.target)) {
        setServicesOpen(false);
      }
      if (
        mobileMenuRef.current &&
        !mobileMenuRef.current.contains(event.target)
      ) {
        setMobileMenuOpen(false);
      }
    }
    if (servicesOpen || mobileMenuOpen) {
      document.addEventListener("mousedown", handleClickOutside);
    } else {
      document.removeEventListener("mousedown", handleClickOutside);
    }
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [servicesOpen, mobileMenuOpen]);

  const menuItems = [
    "Booklets",
    "Business Essentials",
    "Digitizing",
    "Graphics Design",
    "Marketing Materials",
    "Packaging",
    "Photos",
    "Promotional",
    "Signages",
    "Hardware",
    "Super Saver",
  ];

  return (
    <>
      <Head>
        <title>Mecarvi Prints</title>
        <meta name="description" content="Generated by Ahmad" />
      </Head>
      <Navbar />
      <CartSlider />

      <CartProvider>
        <main className="mt-10 lg:mt-22">{children}</main>
        <Toaster position="top-right" reverseOrder={false} />
      </CartProvider>

      {/* Ticker Section */}
      <section>
        <NewsTicker
          text="Mecarvi Prints- Fast Service with Uncompromising Quality | Special Offer: 15% Off Business Cards | Free Shipping on Orders Over $50 | Same-Day Printing Available | Bulk Order Discounts"
          textColor="white"
        />
      </section>

      <footer className="bg-black text-white">
        <div className="relative flex w-full  sm:hidden md:flex ">
          <FooterSection />
        </div>

        {/* Copyright Section */}
        <div className="bg-black border-t border-[#797979] text-center py-4 ">
          <p className="text-[#AAAAAA] text-[15px]">
            Copyright © 2015–2025 by Mecarvi Holdings Group. All Rights
            Reserved.
          </p>
        </div>
      </footer>
    </>
  );
}
